apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-guestbook-frontend
  labels:
    app: java-guestbook
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: java-guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: java-guestbook
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: rishikeshr/java-guestbook-frontend
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GUESTBOOK_API_ADDR
          value: java-guestbook-backend:8080
        - name: JAVA_TOOL_OPTIONS
          value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
        - name: APPDYNAMICS_NETVIZ_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: APPDYNAMICS_NETVIZ_AGENT_PORT
          value: "3892"
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
          limits:
            cpu: 400m
            memory: 500Mi
